Console.WriteLine("Вычисление расстояния между двумя точками в пространстве");
Console.WriteLine("Введите координаты точки А");
Console.Write("X: ");
var x1String = Console.ReadLine();
double x1 = double.Parse(x1String!);
Console.Write("Y: ");
var y1String = Console.ReadLine();
double y1 = double.Parse(y1String!);
Console.Write("Z: ");
var z1String = Console.ReadLine();
double z1 = double.Parse(z1String!);
Console.WriteLine("Введите координаты точки B");
Console.Write("X: ");
var x2String = Console.ReadLine();
double x2 = double.Parse(x2String!);
Console.Write("Y: ");
var y2String = Console.ReadLine();
double y2 = double.Parse(y2String!);
Console.Write("Z: ");
var z2String = Console.ReadLine();
double z2 = double.Parse(z2String!);
double ras = Math.Sqrt(Math.Pow(x2 - x1, 2) + Math.Pow(y2 - y1, 2) + Math.Pow(z2 - z1, 2));
// Console.WriteLine(ras);
Console.WriteLine("\n" + ras.ToString("N2"));
